import { Inter } from "next/font/google";
import { ClerkProvider, ThemeProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import {dark} from "@clerk/themes";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bouquet.Gen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }){
  return (
    <ClerkProvider 
      appearance={{ 
        baseTheme: dark, 
        variables: { 
          colorBackground: '#383139',
          colorPrimary: '#f8d3c5',
        }
      }}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
